version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root directory with package.json
    schedule:
      interval: "weekly" # Weekly updates for security patches
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
      - auto-approve