// src/app/layout.tsx
import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Scene from "@/components/Scene";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'My Portfolio',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.className} bg-black`}>
        <Navbar/>
        {children}
        </body>
        </html>
    );
}